version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: bull
    ports:
      - '5437:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  remote-server:
    build:
      context: .
      dockerfile: test-remote-server/Dockerfile
    container_name: remote-ssh-server
    ports:
      - '2222:22'
    restart: unless-stopped
    volumes:
      - remote_data:/home/user/worker

volumes:
  pgdata:
  remote_data:
